### ISSUE TITLE
Invalid websafe color for FFF000?

### ISSUE THREAD

**Issue by JaneX8** [skratchdot/color-quantize#2]
const colorQuantize = require('color-quantize')
    colorQuantize.websafe('#FFF000')

Results in `FF FF 00` (added spaces for readability). I wonder if this is correct. I found three different sites giving three different answers on the same input.

According to: 
- https://convertingcolors.com/hex-color-FFF000.html results in `FF FF 33`
- https://www.spycolor.com/fff000 results in `FF F0 00`

But https://www.colorhexa.com/fff000 seems to agree with the `color-quantize` package returning the closest websafe color `FF FF 00`. What is the correct answer?

**Comment by skratchdot** [comment]
Original:
- `#FFF000` = `rgb(255, 240, 0)` (https://projects.skratchdot.com/colorify/stats/fff000)

You can rule out `FFF000` as websafe because `f0` for the `G` value is not one of the valid 6 options: `00`, `33`, `66`, `99`, `CC`, `FF`

Also, it looks like this lib (color-quantize), colorhexa, and spycolor all show the following:
- `#FFFF00` = `rgb(255, 255, 0)` (https://projects.skratchdot.com/colorify/stats/ffff00)

That appears to be correct because the difference in `R` is `0`, `G` is `15`, and `B` is `0` for a total of `15`.

convertingcolors.com shows:
- `#FFFF33` = `rgb(255, 255, 51)` (https://projects.skratchdot.com/colorify/stats/ffff33)

which looks incorrect to me because the difference in `R` is `0`, `G` is `15`, and `B` is `51` for a total of `66`, but perhaps they are using a better method for finding a closer websafe color.
